Removed weather controller
IvanLukyanau/LX.StaffScheduler.BE pull request #6
Opened 2024-06-17 14:26 UTC by Rapkup

2024-06-17 15:32 UTC, IvanLukyanau requested changes

2024-06-17 15:32 UTC, IvanLukyanau commented on LX.StaffScheduler.Api/Controllers/WeatherForecastController.cs
> -    public class WeatherForecastController : ControllerBase
Please create new contoller related to your further tasks but without any actions toward to save /Controllers directory.

2024-06-17 15:32 UTC, IvanLukyanau commented on LX.StaffScheduler.Api/Controllers/WeatherForecastController.cs
> -        public IEnumerable<WeatherForecast> Get()
In assembly you have a file of class WeatherForecast so please remove it along with unnecessary controller

2024-06-17 15:32 UTC, IvanLukyanau commented on LX.StaffScheduler.Api/appsettings.Development.json
> +    "DefaultConnection": "Data Source=RAPKUPICH;Initial Catalog=CafeDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFa
can be omitted toward to leave these settings of connection not modified toward to exclude the json file from diff

2024-06-18 10:28 UTC, IvanLukyanau approved these changes

2024-06-18 10:29 UTC, Karisha04 approved these changes
PERFECT!!!!!!!!!

2024-06-18 12:22 UTC, merged